jwt:
    time: 90000
    secret: hello-world1234
posco:
    name: 3기1234
    count: 201234
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&charcterEncoding=utf8&serverTimezone=Asia/Seoul
        username: root
        password: 1234

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&charcterEncoding=utf8&serverTimezone=Asia/Seoul
        username: root
        password: 1234
